language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
install:
    - pip install coverage==4.0.2
script:
    coverage run --source=namealizer --branch test_namealizer.py
after_success:
    - coveralls
