language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
install:
    - pip install coverage==4.0.2
script:
    cd namealizer
    coverage run --branch --source=namealizer.py test_namealizer.py
    cd ..
after_success:
    - coveralls
