language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"
install:
    - pip install coverage coveralls
script:
    cd namealizer
    coverage run --branch --source=namealizer test_namealizer.py
    cd ..
after_success:
    - coveralls
