language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
install:
    - pip install coveralls
script:
    coverage run --source=namealizer test_namealizer.py
after_success:
    - coveralls
