from setuptools import setup
#package_dir={"namealizer": "namealizer"},
setup(name="namealizer",
      packages=["namealizer"],
      version="0.6",
      description="A tool for generating and formatting random words",
      author="Michael Leonard",
      author_email="maybeillrememberit@gmail.com",
      url="https://github.com/LeonardMH/namealizer",
      download_url="https://github.com/LeonardMH/namealizer/tarball/0.6",
      keywords=["random words", "namealizer", "word", "dictionary"],
      package_data={"namealizer": ["dictionaries/*"]},
      scripts=["scripts/namealizer"],
      classifiers=["Development Status :: 4 - Beta",
                   "Environment :: Console",
                   "Intended Audience :: Developers",
                   "License :: OSI Approved :: MIT License",
                   "Operating System :: MacOS :: MacOS X",
                   "Operating System :: Microsoft :: Windows",
                   "Operating System :: POSIX",
                   "Programming Language :: Python",
                   "Topic :: Utilities"])
